### ISSUE TITLE
Different behavior on Android and iOS

### ISSUE THREAD

**Issue by fortunella** [jrquick17/ionic4-auto-complete#45] opened 2020-01-21 19:24 UTC
The component works fine, but the behavior on Android is different than that on iOS.

Android:
- tap the input field
- keyboard opens
- start typing
- select item from the list
- list is closed, keyboard is closed and selected value is taken into the input field

iOS:
- tap the input field
- keyboard opens
- start typing
- select item from the list
- keyboard is closed and list remains open
- select item from the list again
- list is closed and selected value is taken into the input field

This is my code:
```
<ion-auto-complete formControlName="building" #building [dataProvider]="buildingService"
                                [options]="{searchIcon: '', debounce: 100, placeholder: placeholder}"
                                (itemSelected)="changeBuilding()" (autoBlur)="changeBuilding()"></ion-auto-complete>

```

The behavior on iOS is a bit confusing as the user has to select the desired item from the list twice. Is this the expected behavior on iOS or did I configure something wrong?

**Comment by rsivan** [comment] 2020-01-21 21:03
I notice a similar issue, although in my case it is inconsistent: sometimes I need to select twice, and sometimes just once.

**Comment by jrquick17** [comment] 2020-01-22 19:49
I am unable to reproduce using an emulator and do not own an iOS device. I am working on the next release now, can someone verify if this is still an issue in `v2.5.1`?

**Comment by rsivan** [comment] 2020-01-22 23:07
Not reproducible in 2.5.1 for me.

**Comment by jrquick17** [comment] 2020-01-23 03:31
Thanks for the help! I will close this issue. If the problem persists then feel free to open another issue.

**Closed by jrquick17** 2020-01-23 03:31 UTC

**Comment by fortunella** [comment] 2020-02-14 11:30
Sorry for my late response. Lot of work in the last few weeks.

Unfortunately, the strange behavior is still there in 2.5.1. I can reproduce it with my iPhone X device as well as with the simulator of an iPhone 11 in Xcode 11.3.1.

I recorded a short video on the iPhone X to show the behavior. What you can see is that in a first step the keyboard closes and then in a second step the selected item is taken into the text field. As a result I always have to tap an item twice to select it.

Please let me know if I can support you with further info and so on.

![ionic4-autocomplete](https://user-images.githubusercontent.com/17113047/74527267-83b0ae80-4f25-11ea-848d-f9d9a5f0e365.gif)
